package eunai.exception;

// JavaDocs for eunai.exception package generated by ChatGPT
/**
 * Represents a custom exception specific to the {@code eunai} application.
 * Serves as the base class for all application-specific exceptions.
 */
public class EunAiException extends Exception {

    /**
     * Constructs an {@code EunAIException} with the specified detail message.
     *
     * @param message The detail message explaining the cause of the exception.
     */
    public EunAiException(String message) {
        super(message);
    }
}
