package chitti;

import java.util.*;

/**
 * Represents the Chitti chatbot.
 * This class manages the interaction with the user, task storage, and command processing.
 */
public class Chitti {
    private Storage storage;
    private TaskList tasks;
    private Ui ui;
    private Parser parser;
    /**
     * Constructs a Chitti object with the specified file path.
     * Initializes the Ui, Storage, Parser, and loads tasks from the specified file.
     *
     * @param filePath The file path to load tasks from.
     */
    public Chitti(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        parser = new Parser();
        try {
            tasks = new TaskList(storage.loadTasksFromFile());
        } catch (Exception e) {
            System.out.println(e);
            tasks = new TaskList(new ArrayList<>());
        }
        assert ui != null : "Ui instance should not be null";
        assert storage != null : "Storage instance should not be null";
        assert parser != null : "Parser instance should not be null";
    }
    /**
     * Processes the user's input and returns an appropriate response.
     * If the input is "bye", the chatbot will end the conversation.
     * Otherwise, the command will be parsed and executed, and a response will be generated.
     *
     * @param input The user's input.
     * @return The response generated by the chatbot based on the input.
     */
    public String getResponse(String input) {
        if (input.equalsIgnoreCase("bye")) {
            return "Bye! Hope to see you again soon!";
        }
        return parser.handleCommand(input, tasks, ui);
    }
}