package vic;

import vic.actions.Action;
import vic.enums.Command;
import vic.exceptions.UnknownCommandException;
import vic.exceptions.VicException;
import vic.parser.Parser;
import vic.response.ErrorResponse;
import vic.response.IntroResponse;
import vic.response.OutroResponse;
import vic.response.Response;
import vic.storage.Storage;
import vic.tasks.TaskList;
import vic.ui.Ui;

/**
 * The main class for the Vic chatbot.
 */
public class Vic {
    private static final String FILE_NAME = "/vic.txt";
    private static final String FOLDER_PATH = "./data";

    private Storage storage;
    private TaskList taskList;
    private Ui ui;

    /**
     * Constructs a Vic instance for task management.
     *
     * @param fileName   The name of the file where tasks are stored
     * @param folderPath The path to the folder where the file is stored
     */
    public Vic(String fileName, String folderPath) {
        this.ui = new Ui();
        this.storage = new Storage(fileName, folderPath);
        initializeTaskList();
    }

    /**
     * Initializes the task list by loading tasks from the storage.
     * If the file does not exist, it will handle the exception gracefully.
     */
    private void initializeTaskList() {
        try {
            if (!storage.checkFileExists()) {
                throw new VicException();
            }
            this.taskList = storage.load();
        } catch (VicException e) {
            ui.out(e.getMessage());
        }
    }

    /**
     * Handles the user input by parsing the command, executing the appropriate action,
     * and returning the resulting response.
     * This method splits the input string into parts and passes it to `handleCommand`
     * to process the input.
     *
     * @param input The user input to be processed.
     * @return The response generated by processing the input.
     */
    public Response handleRun(String input) {
        if (input.isEmpty()) {
            return new OutroResponse();
        }

        return handleCommand(input.split(" "));
    }

    /**
     * Executes the corresponding action and returns the result as a response.
     *
     * @param responseLst The parts of the user input, where the first element is the command
     *                    and the remaining elements are its arguments.
     * @return The response generated after executing the corresponding action
     * @throws UnknownCommandException if the command is not recognized.
     */
    private Response handleCommand(String... responseLst) {
        Command command = Command.convertText(responseLst[0]);

        try {
            Action actionObject = Parser.parseCommand(command, String.join(" ", responseLst), storage, taskList);
            if (actionObject.isExit()) {
                return new OutroResponse();
            }
            return actionObject.execute();
        } catch (UnknownCommandException e) {
            return new ErrorResponse(e.getMessage());
        }
    }

    /**
     * Starts and runs the Vic chatbot application.
     * It continuously accepts user input and performs actions.
     */
    public void run() {
        ui.out(new IntroResponse().getMessage());

        while (true) {
            String input = ui.readCommand();
            Response response = handleRun(input);
            ui.out(response.getMessage());
            if (response instanceof OutroResponse) {
                break;
            }
        }
    }

    /**
     * The entry point of the application.
     *
     *  @param args Command-line arguments passed to the application. unused.
     */
    public static void main(String[] args) {
        new Vic(FILE_NAME, FOLDER_PATH).run();
    }
}
