package clank.gui;

import clank.Clank;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;

/**
 * Controller for the main GUI.
 */
public class MainWindow extends AnchorPane {
    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;

    private Clank clank;

    private Image userImage = new Image(this.getClass().getResourceAsStream("/images/User.png"));
    private Image clankImage = new Image(this.getClass().getResourceAsStream("/images/Clank.png"));

    /**
     * Initializes the GUI components and ensures the scroll bar follows new messages.
     */
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
    }

    /**
     * Injects the Clank instance into the controller and displays the welcome message.
     *
     * @param clank The Clank chatbot instance.
     */
    public void setClank(Clank clank) {
        this.clank = clank;

        String welcomeMessage = clank.getWelcomeMessage();
        String upcomingTasksMessage = clank.getUpcomingTasksMessage();

        dialogContainer.getChildren().add(DialogBox.getClankDialog(
                welcomeMessage + "\n" + upcomingTasksMessage, clankImage));
    }

    /**
     * Creates two dialog boxes, one echoing user input and the other containing Clank's reply and then appends them to
     * the dialog container. Clears the user input after processing. If the user inputs "bye", the application
     * will exit after a short delay.
     */
    @FXML
    private void handleUserInput() {
        String input = userInput.getText();
        String clankResponse = clank.getResponse(input);

        displayResponse(input, clankResponse);
        userInput.clear();

        if (input.trim().equalsIgnoreCase("bye")) {
            closeApp();
        }
    }

    /**
     * Displays both the user's message and Clank's response in the dialog container.
     *
     * @param userMessage The message input by the user.
     * @param clankResponse The response generated by Clank.
     */
    private void displayResponse(String userMessage, String clankResponse) {
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(userMessage, userImage),
                DialogBox.getClankDialog(clankResponse, clankImage)
        );
    }

    /**
     * Closes the Clank chatbot application.
     */
    private void closeApp() {
        Platform.exit();
    }
}
