package vegetables.gui;

import java.util.ArrayList;

import vegetables.command.CommandHandler;
import vegetables.manager.TaskManager;
import vegetables.storage.TaskStorage;
import vegetables.task.Task;

/**
 * The main logic handler for the Vegetables application.
 * <p>
 * This class initializes the application's core components, including {@link TaskStorage},
 * {@link TaskManager}, and {@link CommandHandler}. It processes user input and returns
 * appropriate responses.
 * </p>
 */
public class VegetablesGui {
    private final CommandHandler commandHandler;

    /**
     * Constructs a {@code VegetablesGUI} instance and initializes the necessary components.
     * <p>
     * This includes loading tasks from storage, managing them through {@link TaskManager},
     * and setting up a {@link CommandHandler} to process user commands.
     * </p>
     */
    public VegetablesGui() {
        TaskStorage taskStorage = new TaskStorage();
        ArrayList<Task> tasks = taskStorage.loadTasks();
        TaskManager taskManager = new TaskManager(tasks);
        this.commandHandler = new CommandHandler(taskManager, taskStorage);
    }

    /**
     * Processes user input and returns the corresponding response.
     * <p>
     * Delegates command execution to the {@link CommandHandler}, which interprets the input
     * and performs the necessary actions.
     * </p>
     *
     * @param input The user's input command.
     * @return The response message generated by executing the command.
     */
    public String getResponse(String input) {
        return commandHandler.executeCommand(input);
    }
}
