package vic.actions;

import vic.response.Response;
import vic.storage.Storage;
import vic.tasks.TaskList;

/**
 * Abstract class for the Bot actions
 */
public abstract class Action {
    protected Storage storage;
    protected TaskList taskList;
    protected String action;

    /**
     * Constructor for class
     */
    public Action(Storage storage, TaskList taskList, String action) {
        this.storage = storage;
        this.taskList = taskList;
        this.action = action;
    }

    /**
     * Executes the specific bot action.
     *
     * @return The response generated by the bot after execution.
     */
    public abstract Response execute();

    /**
     * Determines whether the bot should exit after execution.
     *
     * @return true if the bot should exit, false otherwise.
     */
    public boolean isExit() {
        return false;
    }
}
