package pelopsii.command;

import pelopsii.exception.PelopsIIException;

/**
 * Represents a command that provides help information to the user.
 */
public class HelpCommand extends Command {

    /**
     * Executes the help command, displaying a list of available commands.
     *
     * @throws PelopsIIException If an error occurs while displaying the message.
     */
    @Override
    public void execute() throws PelopsIIException {
        StringBuilder sb = new StringBuilder();
        sb.append("Please use one of the following commands:").append("\n");
        sb.append("bye").append("\n");
        sb.append("list").append("\n");
        sb.append("todo").append("\n");
        sb.append("deadline").append("\n");
        sb.append("event").append("\n");
        sb.append("mark").append("\n");
        sb.append("unmark").append("\n");
        sb.append("delete").append("\n");
        sb.append("undo").append("\n");
        sb.append("find");
        this.response = sb.toString();
        this.ui.showMessageToUser(sb.toString());
    }

    /**
     * Retrieves the response generated by the help command.
     *
     * @return A string containing the help message.
     */
    @Override
    public String getResponse() {
        return this.response;
    }
}
